### ISSUE TITLE
Quick Equipping Is no longer around

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#317] opened 2017-02-21 12:04 UTC
In-Game report from omnitricks:
Revision info: Server revision 4d1608b1653733bf2f6033594db76b1b2de9cc8a compiled on: 2017-02-21

Before the rebase we could just put equippables in the bottom right icon and it will immediately be equipped or will replace whatever is in the corresponding slot.

**Comment by msgerbs** [comment] 2017-02-21 16:54
Please re-add this!

**Comment by tortellinitony** [comment] 2017-02-23 07:08
Duplicate of #275.

**Closed as completed by tortellinitony** 2017-02-23 07:08 UTC
