### ISSUE TITLE
Crashed by hallucination

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#330] opened 2017-02-23 02:02 UTC
In-Game report from ugonsthemad:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-02-21

>General description of the issue
Got crashed by an apparent hallucination.
>What you expected to happen
Not to crash, just to suffer the effects of the hallucination.

>What actually happened
It crashed whence experiencing either the singularity hallucination or the C4 in hand one.

>Steps to reproduce if possible

Get hallucinated by various methods, like stings or gas.

**Comment by tortellinitony** [comment] 2017-02-23 07:07
Duplicate of #284

**Closed as completed by tortellinitony** 2017-02-23 07:07 UTC
