### ISSUE TITLE
skeletal minibar in ash walker nest is invisible

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#382] opened 2017-03-01 17:05 UTC
In-Game report from cacogen:
Revision info: Server revision bc0502d97f23d9ffa3a60989e7e58cbac3ef53ac compiled on: 2017-03-01

"i can't get the candles today, brendonna"

**Comment by tortellinitony** [comment] 2017-03-03 04:04
Duplicate of #218

**Closed as completed by tortellinitony** 2017-03-03 04:04 UTC
