### ISSUE TITLE
Chamelon HUD Glasses are broken

### ISSUE THREAD

**Issue by ghost** [HippieStationArchive/HippieStation13-2#424] opened 2017-03-07 20:07 UTC
In-Game report from jamiehankins:
Revision info: Server revision 0000000000000000000000000000000000000000 compiled on: 2017-03-07

>General description of the issue

They don't fucking work

>What you expected to happen

They work

>What actually happened

A runtime happens:
```[19:55:05] Runtime in chameleon.dm, line 87: Cannot read /obj/item/device/pda/clown (/obj/item/device/pda/clown).icon_state
proc name: initialize disguises (/datum/action/item_action/chameleon/change/proc/initialize_disguises)
src: Chameleon Change (/datum/action/item_action/chameleon/change)
call stack:
Chameleon Change (/datum/action/item_action/chameleon/change): initialize disguises()
PDA (/obj/item/device/pda/chameleon): New()
the PDA painter (/obj/machinery/pdapainter): New(the floor (102,121,1) (/turf/open/floor/plasteel/blue/side))
```

>Steps to reproduce if possible

Click the fucking HUD button

**Comment by tortellinitony** [comment] 2017-03-07 20:08
duplicate of #421

**Closed as completed** 2017-03-07 20:10 UTC
